name: refillproo
description: A new Flutter project

publish_to: 'none' # Remove this line if you are publishing the package

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  location: ^8.0.0
  geolocator: ^13.0.4
  permission_handler: ^11.4.0
  http: ^1.3.0
  logging: ^1.3.0
  cupertino_icons: ^1.0.8 # Ensure this is correctly aligned and not commented out

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
    

flutter:
  uses-material-design: true

  assets:
    - images/

